#!/bin/sh
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
export PROJECTS=$HOME/Git
export DOTFILES=$HOME/Git/__dotfiles__

alias todo='vim ~/host/Desktop/todo.txt'

# fancy ssh-stuff!
#export SSH_AUTH_SOCK=~/.ssh/ssh-agent.$HOSTNAME.sock
function auth() {
	eval `ssh-agent` ; ssh-add
#	ssh-add -l 2>/dev/null >/dev/null
#	if [ $? -ge 2 ]; then
#	  ssh-agent -a "$SSH_AUTH_SOCK" >/dev/null
#	fi
}
#eval `ssh-agent`
#ssh-add

FILES=$( find $DOTFILES -name sourceme.sh )
for file in $FILES ; do
	echo "Sourcing: $file"
	source $file
done

source ./rand_bg
rand_bg

if [ -z "$PS1" ]; then
    echo "---===[[[ this shell is not interactive ]]]===---"
else
    # basic interactive expectations
    echo "---===[[[ THIS SHELL IS INTERACTIVE ]]]===---"
    alias ls='ls --color=auto'
    alias sra='ssh robertames.com'

    rand_bg

    # delegate prompt activity to separate script
    function prompt_command {
        export PS1=$( $DOTFILES/bash/prompt )
    }
    export PROMPT_COMMAND=prompt_command
fi
